# Generated by Django 2.2.7 on 2020-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
